// =======================================================
// This file is auto generated by [DataConvertor for Excel Lite] convertor,
// do not edit by youself!
// >>>> by HuMinghua <<<<  Aug 8, 2021 at 6:26:47 PM
// ======================================================


import Foundation


private let AUTO_PLIST_SHEET1_PATH = Bundle.main.path(forResource: "Sheet1", ofType: "plist")

private let AUTO_PLIST_SHEET1_INDEX_TITLE = 0   // TITLE
private let AUTO_PLIST_SHEET1_INDEX_VERSE = 1   // VERSE
private let AUTO_PLIST_SHEET1_INDEX_LINE = 2   // LINE


class TestbibManager {

    public static let sharedManager = TestbibManager()
    private init(){}

    private var _sheet1s = [Sheet1]()

    func allSheet1s() -> [Sheet1]{

        if _sheet1s.count > 0 {
            return _sheet1s
        }

        if let allDatas = NSArray(contentsOfFile: AUTO_PLIST_SHEET1_PATH!) {

            for array in allDatas {
                guard let array = array as? [AnyObject] else {continue}

                let sheet1 = Sheet1()
                sheet1.tITLE = array[AUTO_PLIST_SHEET1_INDEX_TITLE] as? String // TITLE
                sheet1.vERSE = array[AUTO_PLIST_SHEET1_INDEX_VERSE] as? String // VERSE
                sheet1.lINE = array[AUTO_PLIST_SHEET1_INDEX_LINE] as? String // LINE
                _sheet1s.append(sheet1)
            }
        }
        return _sheet1s
    }
}