// =======================================================
// This file is auto generated by [DataConvertor for Excel Lite] convertor,
// do not edit by youself!
// >>>> by HuMinghua <<<<  Aug 8, 2021 at 6:26:47 PM
// ======================================================


import Foundation


class Sheet1 {
    var tITLE : String? = nil; // TITLE
    var vERSE : String? = nil; // VERSE
    var lINE : String? = nil; // LINE
}