// =======================================================
// This file is auto generated by [DataConvertor for Excel Lite] convertor,
// do not edit by youself!
// >>>> by HuMinghua <<<<  Aug 8, 2021 at 6:26:47 PM
// ======================================================

package database;


public class TestbibObjects {


    public class Sheet1 {

        private String tITLE;
        private String vERSE;
        private String lINE;

        /**
         * @return the tITLE
         */
        public String getTITLE() {
            return tITLE;
        }

        /**
         * @param tITLE
         *            the tITLE to set
         */
        public void setTITLE(String tITLE) {
            this.tITLE = tITLE;
        }

        /**
         * @return the vERSE
         */
        public String getVERSE() {
            return vERSE;
        }

        /**
         * @param vERSE
         *            the vERSE to set
         */
        public void setVERSE(String vERSE) {
            this.vERSE = vERSE;
        }

        /**
         * @return the lINE
         */
        public String getLINE() {
            return lINE;
        }

        /**
         * @param lINE
         *            the lINE to set
         */
        public void setLINE(String lINE) {
            this.lINE = lINE;
        }
    }

    }
